import { CLEAR_FRAMES, Detection, Triage, distanceBucketFor, earconFor, tierFor, utteranceFor, zoneFor } from '../triage';
const W = 640; const H = 384;
function box(frameIndex: number, trackId = 1, objClass = 'person', cx = .5, hr = .6): Detection { const w = 64; const h = hr * H; return { frameIndex, trackId, objClass, x1: cx * W - w / 2, y1: (H - h) / 2, x2: cx * W + w / 2, y2: (H + h) / 2, frameWidth: W, frameHeight: H }; }
function play(triage: Triage, frames: Detection[][]) { return frames.flatMap((detections, i) => { triage.observeAll(detections); return triage.emit(i); }); }
const held = (count: number, trackId = 1, cx = .5, hr = .6, start = 0) => Array.from({ length: count }, (_, i) => [box(start + i, trackId, 'person', cx, hr)]);
test('ports zone, bucket, utterance and tier table', () => { expect(zoneFor(box(0, 1, 'person', .1))).toBe('left'); expect(distanceBucketFor(box(0, 1, 'person', .5, .45))).toBe('mid'); expect(tierFor('center', 'near')).toBe('danger'); expect(tierFor('left', 'near')).toBe('warning'); expect(tierFor('center', 'mid', true)).toBe('warning'); expect(tierFor('center', 'far', true, true)).toBe('silent'); expect(utteranceFor('person', 'center', 'danger')).toBe('Stop - person ahead'); expect(earconFor('left', 'warning')).toBe('panned_tone_left'); });
test('debounces at three frames', () => { expect(play(new Triage(), held(2))).toHaveLength(0); expect(play(new Triage(), held(3)).map((e) => e.tier)).toEqual(['danger']); });
test('re-announces after clear window', () => { const frames = held(5).concat(Array.from({ length: CLEAR_FRAMES }, () => [])); frames.push(...held(5, 1, .5, .6, frames.length)); expect(play(new Triage(), frames).filter((e) => e.spoken)).toHaveLength(2); });
test('danger pre-empts a warning', () => { const frames = Array.from({ length: 3 }, (_, i) => [box(i, 1, 'person', .1), box(i, 2, 'car', .5)]); const t = new Triage(); const spoken = play(t, frames); expect(spoken.map((e) => e.tier)).toEqual(['danger']); expect(t.log.some((e) => e.preempted && e.tier === 'warning')).toBe(true); });
