/// <reference types="expo/types" />

// NOTE: This file is generated by Expo (`npx expo start`/`expo customize`).
// It is committed here so that `npm install && npx tsc --noEmit` type-checks on
// a fresh clone without first having to start the dev server.
