import { useMemo, useState } from 'react';
import type { ReadonlyFrameProcessor } from 'react-native-vision-camera';
import { useFrameProcessor } from 'react-native-vision-camera';
import { useTensorflowModel } from 'react-native-fast-tflite';
import { useResizePlugin } from 'vision-camera-resize-plugin';
import { useRunOnJS } from 'react-native-worklets-core';
import type { PerceptionAlert } from '@/api/types';
import { decodeYoloOutput } from '@/lib/yoloDecoder';
import { Triage } from '@/lib/triage';

// Generated by scripts/export_yolo_tflite.py. Native builds must not proceed
// until this file exists; TypeScript can still validate the integration seam.
const MODEL = require('../../assets/models/yolo11n.tflite') as number;

export interface PerceptionStream {
  connected: boolean; lastAlert: PerceptionAlert | null; framesProcessed: number;
  unavailableReason: 'not_implemented' | 'no_camera' | 'permission_denied' | 'model_missing' | null;
  statusText: string; frameProcessor: ReadonlyFrameProcessor | undefined;
}

export function usePerceptionStream(): PerceptionStream {
  const modelState = useTensorflowModel(MODEL, 'core-ml');
  const { resize } = useResizePlugin();
  const [lastAlert, setLastAlert] = useState<PerceptionAlert | null>(null);
  const [framesProcessed, setFramesProcessed] = useState(0);
  const triage = useMemo(() => new Triage(), []);
  const publishAlert = useRunOnJS((event: PerceptionAlert) => setLastAlert(event), [setLastAlert]);
  const countFrame = useRunOnJS(() => setFramesProcessed((value) => value + 1), [setFramesProcessed]);
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet';
    if (modelState.state !== 'loaded') return;
    const input = resize(frame, { scale: { width: 640, height: 640 }, pixelFormat: 'rgb', dataType: 'uint8' });
    const output = modelState.model.runSync([input])[0];
    if (!output) return;
    const detections = decodeYoloOutput(output as Float32Array | Uint8Array, modelState.model.outputs[0]?.shape ?? [], frame.width, frame.height, Math.round(performance.now()));
    triage.observeAll(detections);
    triage.emit().forEach((event) => publishAlert({ frame_index: event.frameIndex, spoken_frame: event.spokenFrame, track_id: event.trackId, obj_class: event.objClass, zone: event.zone, distance: event.distance, tier: event.tier, approaching: event.approaching, utterance: event.utterance, earcon: event.earcon, max_latency_ms: event.maxLatencyMs, spoken: event.spoken, preempted: event.preempted }));
    countFrame();
  }, [modelState, resize, triage, publishAlert, countFrame]);
  const unavailableReason = modelState.state === 'error' ? 'model_missing' : null;
  const statusText = modelState.state === 'error' ? `On-device model unavailable: ${modelState.error.message}` : modelState.state === 'loaded' ? 'On-device YOLO model is loaded; alerts stay on the phone.' : 'Loading the on-device YOLO model.';
  return { connected: modelState.state === 'loaded', lastAlert, framesProcessed, unavailableReason, statusText, frameProcessor };
}
